[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310']
include = '\\.pyi?$'
exclude = '''
/(\.eggs|\.git|\.hg|\.mypy_cache|\.tox|\.venv|__pycache__|build|dist)/
'''

[tool.isort]
profile = "black"
line-length = 100
skip_gitignore = true
ensure_newline_before_comments = true
force_grid_wrap = 0
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true
single_line_output = 0
indent = "    "
exclude = ["\\.venv", "build", "dist"]
